# Generated by Django 5.2.6 on 2025-11-25 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "game_image",
                    models.ImageField(upload_to="main_game/", verbose_name="image"),
                ),
            ],
            options={
                "verbose_name": "Main Game",
                "verbose_name_plural": "Main Games",
            },
        ),
        migrations.CreateModel(
            name="LevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_percent",
                    models.FloatField(
                        default=100,
                        help_text="Percent of total score used for level calculation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_index", models.PositiveIntegerField(default=1)),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer_1", models.CharField(max_length=255, verbose_name="Answer 1")),
                ("answer_2", models.CharField(max_length=255, verbose_name="Answer 2")),
                ("answer_3", models.CharField(max_length=255, verbose_name="Answer 3")),
                ("answer_4", models.CharField(max_length=255, verbose_name="Answer 4")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        verbose_name="Status",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("1", "Answer 1"),
                            ("2", "Answer 2"),
                            ("3", "Answer 3"),
                            ("4", "Answer 4"),
                        ],
                        max_length=1,
                        verbose_name="Correct Answer",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="Explanation"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="question_info/files/",
                        verbose_name="File or Image",
                    ),
                ),
                (
                    "main_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_game",
                        to="main.getcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Game score")),
                ("step", models.IntegerField(default=1, verbose_name="step")),
                ("skipped", models.JSONField(default=list)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_r",
                        to="main.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_r",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Game Connection",
                "verbose_name_plural": "User-Game Connections",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_question", models.PositiveIntegerField(default=0)),
                (
                    "main_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.getcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "main_game")},
            },
        ),
    ]
